### ISSUE TITLE
Unable to get tests to pass

### ISSUE THREAD

**Issue by z3ht** [ResearchSoftwareActions/EnsureCleanNotebooksAction#17]
Hello,

I'm trying to use this action with my Python project but am getting the following error message:

```
Run ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at lint (/home/runner/work/_actions/ResearchSoftwareActions/EnsureCleanNotebooksAction/1.1/dist/index.js:849:23)
    at Walker.<anonymous> (/home/runner/work/_actions/ResearchSoftwareActions/EnsureCleanNotebooksAction/1.1/dist/index.js:72:22)
    at Walker.emit (events.js:210:5)
    at Object.emitSingleEvents [as emitNodeType] (/home/runner/work/_actions/ResearchSoftwareActions/EnsureCleanNotebooksAction/1.1/dist/index.js:458:13)
    at Walker.module.exports.191.Walker._wLstatHandler (/home/runner/work/_actions/ResearchSoftwareActions/EnsureCleanNotebooksAction/1.1/dist/index.js:179:19)
    at /home/runner/work/_actions/ResearchSoftwareActions/EnsureCleanNotebooksAction/1.1/dist/index.js:197:12
    at FSReqCallback.oncomplete (fs.js:159:5)
```

I am very new to using Github workflows so I may be doing something dumb but I was able to get other actions working properly. The following is my workflow file: 

```
name: notebook

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  clear:
    name: clear notebook
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      - name: Ensure clear Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
```

Any help would be appreciated.

I read through a bit of the source code and noticed the project uses Node so I tried adding the following to my job:
```
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
```
but I got the same error message.
